services:
  gateway:
    build: ./gateway
    ports:
      - "80:80"
    depends_on:
      - app
  
  app:
    build: ./app
    restart: on-failure
    env_file:
      - ./app/.env
    depends_on:
      db:
        condition: service_healthy

  db:
    build: ./db
    env_file: ./db/.env
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d app"]
      interval: 10s
      retries: 3
      timeout: 5s 

volumes:
  db:

networks:
  default:
    driver: bridge
